
# GET USUARIOS

GET http://localhost:4000/api/v1/usuario/



###
# GET USUARIO

GET http://localhost:4000/api/v1/usuario/eb4fc4c3-1c25-4d73-a930-97eb7d992dc6


###
# INSERT USUARIO

POST http://localhost:4000/api/v1/usuario/ 
Content-Type: application/json

{
    "nombre": "Julian",
    "apellido": "Torossian",
    "mail": "jtorossian@gaci.com.ar",
    "usuario": "jtorossian",
    "password": "G3U4IjzqPdNqJSDPrePNhg==",
    "color": "#41482F",
    "rol": [
        "ADMIN"
    ]
}


###
# UPDATE USUARIO

PATCH http://localhost:4000/api/v1/usuario/3c9000b1-c663-450d-b59c-7e3f5dcfa062
Content-Type: application/json

{
    "nombre": "Julian",
    "apellido": "Torossian"
}


###
# Iniciar Sesion

GET http://localhost:4000/api/v1/usuario/gestion/iniciarSesion?usuario=juli1&password=G3U4IjzqPdNqJSDPrePNhg==


###
# GET USUARIO PREFERENCIAS

GET http://localhost:4000/api/v1/usuario/1138c392-9ed2-45cb-858b-3de37745cb62/preferencias